报表日期: report_date
货币资金: cash and cash equivalents
存放中央银行款: for the central bank
结算准备金: Balance Deposit
贵金属: precious metal
存放同业款项 Deposits in other banks
拆出资金 Loans to other banks
拆放同业 Call Loan to Banks
拆放金融性公司 Put down the financial company
存放联行款项 Deposits in correspondent banks
存出发钞基金 The note-issuing fund
衍生金融工具资产 Derivative financial instruments
交易性金融资产 transaction monetary assets