报表日期: report_date
#profit_statement
一、营业总收入: gross_revenue
营业收入: operating_income
利息收入: interest_income
已赚保费: earned_premium
手续费及佣金收入: fee_and_commission_income
房地产销售收入: real_estate_sales
其他业务收入: other_operating_revenue
二、营业总成本: total_operating_cost
营业成本: operating_cost
利息支出: interest_expense
手续费及佣金支出: fee_and_commission_expenses
房地产销售成本: real_estate_sales_cost
研发费用: research_development_expense
退保金: surrender_value
赔付支出净额: net_payments_for_insurance_claims
提取保险合同准备金净额: net_provision_for_insurance_contracts
保单红利支出: bond_insurance_expense
分保费用: amortized_reinsurance_expenditures
其他业务成本: other_operational_costs
营业税金及附加: business_tariff_and_annex
销售费用: sales_costs
管理费用: management_cost
财务费用: finance_charges
资产减值损失: asset_impairment_loss
公允价值变动收益: changes_in_the_fair_value_earnings
投资收益: investment_income
对联营企业和合营企业的投资收益: associated_enterprises_and_joint_venture_investment_income
汇兑收益: foreign_exchange_earnings
期货损益: profit_and_loss_of_futures
托管收益: managed_earnings
补贴收入: subsidize_revenue
其他业务利润: income_from_other_operation
三、营业利润: operating_profit
营业外收入: non_operating_income
营业外支出: nonbusiness_expenditure
非流动资产处置损失: disposal_loss_on_noncurrent_liability
利润总额: total_Profits
所得税费用: income_tax_expenses
未确认投资损失: unrealised_investment_losses
四、净利润: net_profit
归属于母公司所有者的净利润: net_profit_attributable_to_parent_company_owners
少数股东损益: minority_interests
五、每股收益: earnings_per_share
基本每股收益: basic_earnings_per_share_yuan
稀释每股收益: diluted_earnings_per_share_yuan
六、其他综合收益: oci
七、综合收益总额: aggregate_comprehensive_income
归属于母公司所有者的综合收益总额: total_comprehensive_income_attributable_to_parent_company_owners
归属于少数股东的综合收益总额: total_comprehensive_income_attributable_to_minority_shareholders

#balance_sheet
货币资金: cash_and_cash_equivalents
结算备付金: deposit_reservation_for_balance
拆出资金: loans_to_others_banks
交易性金融资产: transaction_monetary_assets
衍生金融资产: derivative_financial_assets
应收票据: notes_receivable
应收账款: account_receivable
预付款项: prepayments
应收保费: premiums receivable
应收分保账款: reinsurance_accounts_receivable
应收分保合同准备金: receivable_from_subcontracting_reserves
应收利息: interest_receivable
应收股利: dividend_receivable
其他应收款: other_receivables
应收出口退税: export_drawback_receivable
应收补贴款: allowance_receivable
应收保证金: margin_receivable
内部应收款: internal_receivables
买入返售金融资产: redemptory_monetary_capital_for_sale
存货: inventory
待摊费用: deferred_and_prepaid_expenses
待处理流动资产损失: current_asset_losses_in_suspense
一年内到期的非流动资产: noncurrent_assets_matured_within_a_year
其他流动资产: other_current_assets
流动资产合计: total_current_assets
发放贷款及垫款: loans_and__advance
可供出售金融资产: financial_assets_available_for_sale
持有至到期投资: held-to-maturity_investments
长期应收款: long-term_account_receivable
长期股权投资: long-term_equity_investments
其他长期投资: other_long-term_investment
投资性房地产: investment_real_estate
固定资产原值: original_value_of_fixed_assets
累计折旧: accumulated_depreciation
固定资产净值: fixed_assets-net_value
固定资产减值准备: fixed_assets_depreciation_reserves
固定资产净额: net_value_of_fixed_assets
在建工程: construction_in_progress
工程物资: project_goods_and_material
固定资产清理: disposal_of_fixed_assets
生产性生物资产: capitalized_biological_assets
公益性生物资产: non-profit_living_assets
油气资产: oil-and-gas_assets
无形资产: intangible_asset
开发支出: development_disbursement
商誉: goodwill
长期待摊费用: long-term_deferred_and_prepaid_expenses
股权分置流通权: circulation_right_for_equity_separatio
递延所得税资产: deferred_income_tax_assets
其他非流动资产: other_non-current_assets
非流动资产合计: total_non-current_assets
资产总计: total_assets
短期借款: short-term_borrowings
向中央银行借款: borrowings_from_central_bank
吸收存款及同业存放: deposits_from_customers_and_interbank
拆入资金: loans_from_other_banks
交易性金融负债: transaction_financial_liabilities
衍生金融负债: derivative_financial_liability
应付票据: notes_payable
应付账款: accounts_payable
预收款项: account_collected_in-advance
卖出回购金融资产款: financial_assets_sold_for_repurchase
应付手续费及佣金: handling_charges_and_commissions_payable
应付职工薪酬: employee_pay_payable
应交税费: tax_payable
应付利息: accrued_interest_payable
应付股利: dividends_payable
其他应交款: other_payable_to_government
应付保证金: margin_requirement
内部应付款: internal_accouts_receivable
其他应付款: other_payables
预提费用: accrued_expenses
预计流动负债: expected_to_current_liabilities
应付分保账款: dividend_payable_for_reinsurance
保险合同准备金: provision_for_insurance_contracts
代理买卖证券款: receivings_from_vicariously_traded_securities
代理承销证券款: acting_underwriting_securities
国际票证结算: international_ticket_settlement
国内票证结算: domestic_ticket_settlement
递延收益: deferred_income
应付短期债: short-term_debentures_payable
一年内到期的非流动负债: non-current_liabilities_due_within_one_year
其他流动负债: other_current_liabilities
流动负债合计: total_current_liabilities
长期借款: long-term_loans
应付债券: bonds_payable
长期应付款: long-term_account_payable
专项应付款: special_payables
预计非流动负债: expect_non-current_liabilities
递延所得税负债: deferred_income_tax_liabilities
其他非流动负债: other_non-current_liabilities
非流动负债合计: total_non-current_liabilities
负债合计: total_liabilities
实收资本(或股本): paid-up_capital
资本公积: capital_reserves
库存股: treasury_stock
专项储备: special_reserves
盈余公积: surplus_reserves
一般风险准备: generic_risk_reserve
未确定的投资损失: uncertain_investment_losses
未分配利润: undistributed_profit
拟分配现金股利: distribution_of_cash_dividend
外币报表折算差额: translation_reserve
归属于母公司股东权益合计: attributable_to_the_parent_company_shareholders_equity_in_total
少数股东权益: minority_interest
所有者权益(或股东权益)合计: shareholders_equity_combined
负债和所有者权益(或股东权益)总计: liabilities_and_shareholders_equity_in_total