报表日期: report_date
#profit_statement
一、营业总收入: gross_revenue
营业收入: operating_income
利息收入: interest_income
已赚保费: earned_premium
手续费及佣金收入: fee_and_commission_income
房地产销售收入: real_estate_sales
其他业务收入: other_operating_revenue
二、营业总成本: total_operating_cost
营业成本: operating_cost
利息支出: interest_expense
手续费及佣金支出: fee_and_commission_expenses
房地产销售成本: real_estate_sales_cost
研发费用: research_development_expense
退保金: surrender_value
赔付支出净额: net_payments_for_insurance_claims
提取保险合同准备金净额: net_provision_for_insurance_contracts
保单红利支出: bond_insurance_expense
分保费用: amortized_reinsurance_expenditures
其他业务成本: other_operational_costs
营业税金及附加: business_tariff_and_annex
销售费用: sales_costs
管理费用: management_cost
财务费用: finance_charges
资产减值损失: asset_impairment_loss
公允价值变动收益: changes_in_the_fair_value_earnings
投资收益: investment_income
对联营企业和合营企业的投资收益: associated_enterprises_and_joint_venture_investment_income
汇兑收益: foreign_exchange_earnings
期货损益: profit_and_loss_of_futures
托管收益: managed_earnings
补贴收入: subsidize_revenue
其他业务利润: income_from_other_operation
三、营业利润: operating_profit
营业外收入: non_operating_income
营业外支出: nonbusiness_expenditure
非流动资产处置损失: disposal_loss_on_noncurrent_liability
利润总额: total_Profits
所得税费用: income_tax_expenses
未确认投资损失: unrealised_investment_losses
四、净利润: net_profit
归属于母公司所有者的净利润: net_profit_attributable_to_parent_company_owners
少数股东损益: minority_interests
五、每股收益: earnings_per_share
基本每股收益: basic_earnings_per_share_yuan
稀释每股收益: diluted_earnings_per_share_yuan
六、其他综合收益: oci
七、综合收益总额: aggregate_comprehensive_income
归属于母公司所有者的综合收益总额: total_comprehensive_income_attributable_to_parent_company_owners
归属于少数股东的综合收益总额: total_comprehensive_income_attributable_to_minority_shareholders

#balance_sheet
货币资金: cash_and_cash_equivalents
结算备付金: deposit_reservation_for_balance
拆出资金: loans_to_others_banks
交易性金融资产: transaction_monetary_assets
衍生金融资产: derivative_financial_assets
应收票据: notes_receivable
应收账款: account_receivable
预付款项: prepayments
应收保费: premiums_receivable
应收分保账款: reinsurance_accounts_receivable
应收分保合同准备金: receivable_from_subcontracting_reserves
应收利息: interest_receivable
应收股利: dividend_receivable
其他应收款: other_receivables
应收出口退税: export_drawback_receivable
应收补贴款: allowance_receivable
应收保证金: margin_receivable
内部应收款: internal_receivables
买入返售金融资产: redemptory_monetary_capital_for_sale
存货: inventory
待摊费用: deferred_and_prepaid_expenses
待处理流动资产损益: current_asset_losses_in_suspense
一年内到期的非流动资产: noncurrent_assets_matured_within_a_year
其他流动资产: other_current_assets
流动资产合计: total_current_assets
发放贷款及垫款: loans_and__advance
可供出售金融资产: financial_assets_available_for_sale
持有至到期投资: held_to_maturity_investments
长期应收款: long_term_account_receivable
长期股权投资: long_term_equity_investments
其他长期投资: other_long_term_investment
投资性房地产: investment_real_estate
固定资产原值: original_value_of_fixed_assets
累计折旧: accumulated_depreciation
固定资产净值: fixed_assets_net_value
固定资产减值准备: fixed_assets_depreciation_reserves
固定资产净额: net_value_of_fixed_assets
在建工程: construction_in_progress
工程物资: project_goods_and_material
固定资产清理: disposal_of_fixed_assets
生产性生物资产: capitalized_biological_assets
公益性生物资产: non_profit_living_assets
油气资产: oil_gas_assets
无形资产: intangible_asset
开发支出: development_disbursement
商誉: goodwill
长期待摊费用: long_term_deferred_and_prepaid_expenses
股权分置流通权: circulation_right_for_equity_separatio
递延所得税资产: deferred_income_tax_assets
其他非流动资产: other_non_current_assets
非流动资产合计: total_non_current_assets
资产总计: total_assets
短期借款: short_term_borrowings
向中央银行借款: borrowings_from_central_bank
吸收存款及同业存放: deposits_from_customers_and_interbank
拆入资金: loans_from_other_banks
交易性金融负债: transaction_financial_liabilities
衍生金融负债: derivative_financial_liability
应付票据: notes_payable
应付账款: accounts_payable
预收款项: account_collected_in_advance
卖出回购金融资产款: financial_assets_sold_for_repurchase
应付手续费及佣金: handling_charges_and_commissions_payable
应付职工薪酬: employee_pay_payable
应交税费: tax_payable
应付利息: accrued_interest_payable
应付股利: dividends_payable
其他应交款: other_payable_to_government
应付保证金: margin_requirement
内部应付款: internal_accouts_receivable
其他应付款: other_payables
预提费用: accrued_expenses
预计流动负债: expected_to_current_liabilities
应付分保账款: dividend_payable_for_reinsurance
保险合同准备金: provision_for_insurance_contracts
代理买卖证券款: receivings_from_vicariously_traded_securities
代理承销证券款: acting_underwriting_securities
国际票证结算: international_ticket_settlement
国内票证结算: domestic_ticket_settlement
递延收益: deferred_income
应付短期债券: short_term_debentures_payable
一年内到期的非流动负债: non_current_liabilities_due_within_one_year
其他流动负债: other_current_liabilities
流动负债合计: total_current_liabilities
长期借款: long_term_loans
应付债券: bonds_payable
长期应付款: long_term_account_payable
专项应付款: special_payables
预计非流动负债: expect_non_current_liabilities
递延所得税负债: deferred_income_tax_liabilities
其他非流动负债: other_non_current_liabilities
非流动负债合计: total_non_current_liabilities
负债合计: total_liabilities
实收资本(或股本): paid_up_capital
资本公积: capital_reserves
库存股: treasury_stock
专项储备: special_reserves
盈余公积: surplus_reserves
一般风险准备: generic_risk_reserve
未确定的投资损失: uncertain_investment_losses
未分配利润: undistributed_profit
拟分配现金股利: distribution_of_cash_dividend
外币报表折算差额: translation_reserve
归属于母公司股东权益合计: attributable_to_the_parent_company_shareholders_equity_in_total
少数股东权益: minority_interest
所有者权益(或股东权益)合计: shareholders_equity_combined
负债和所有者权益(或股东权益)总计: liabilities_and_shareholders_equity_in_total


#cash_flow
报告期: report_date
销售商品、提供劳务收到的现金: cash_flows_from_operation_activities
客户存款和同业存放款项净增加额: customer_deposits_and_interbank_deposit_payment_net_increase
向中央银行借款净增加额: net_increase_in_borrowing_from_the_central_bank
向其他金融机构拆入资金净增加额: net_increase_in_funds_borrowed_from_other_financial_institutions
收到原保险合同保费取得的现金: received_the_original_contract_of_insurance_premium_cash
收到再保险业务现金净额: receive_reinsurance_business_net_cash
保户储金及投资款净增加额: insured_savings_and_investment_fund_net_increase
处置交易性金融资产净增加额: disposal_of_tradable_financial_asset_net_increase
收取利息、手续费及佣金的现金: interest_fee_and_commission_in_cash
拆入资金净增加额: loans_from_other_banks_increase
回购业务资金净增加额: repurchase_net_increase_business_financing
收到的税费返还: refunds_of_taxes
收到的其他与经营活动有关的现金: other_related_to_business_activities_of_cash_received
经营活动现金流入小计: cash_inflows_from_operating_activities
购买商品、接受劳务支付的现金: cash_paid_for_goods_purchased_and_labor_services_received
客户贷款及垫款净增加额: customer_loans_and_advances_net_increase
存放中央银行和同业款项净增加额: for_the_central_bank_and_trade_net_increase
支付原保险合同赔付款项的现金: original_insurance_contract_claims_payment_in_cash
支付利息、手续费及佣金的现金: pay_the_interest_charges_and_commission_in_cash
支付保单红利的现金: cash_dividend_payment_policy
支付给职工以及为职工支付的现金: Cash_paid_to_employee_and_for_employee
支付的各项税费: tax_payments
支付的其他与经营活动有关的现金: other_cash_payment_related_to_operating_activities
经营活动现金流出小计: Cash_outflow_for_operating_activities
经营活动产生的现金流量净额: net_amount_of_cash_flow_that_the_business_activities_generate
收回投资所收到的现金: Cash_received_form_return_of
取得投资收益所收到的现金: Obtain_investment_income_received_in_cash
处置固定资产、无形资产和其他长期资产所收回的现金净额: disposal_fixed_intangible_assets_other_long_term_assets_net_cash
处置子公司及其他营业单位收到的现金净额: net_cash__from_disposal_of_subsidiaries_other_business_entities
收到的其他与投资活动有关的现金: Other_cash_received_relating_to_investing_activities
减少质押和定期存款所收到的现金: Reduce_cash_pledge_and_deposit_received
投资活动现金流入小计: Cash_inflow_from_investment_activities
购建固定资产、无形资产和其他长期资产所支付的现金: construction_of_fixed_intangible_other_long_term_assets__cash
投资所支付的现金: Cash_paid_to_acquire_investments
质押贷款净增加额: the_pledge_loan_net_increase
取得子公司及其他营业单位支付的现金净额: net_cash_for_acquisition_subsidiaries_other_business_entities
支付的其他与投资活动有关的现金: Other_cash_payments_relating_to_investing_activities
增加质押和定期存款所支付的现金: Increase_the_pledge_and_the_deposit_paid_by_cash
投资活动现金流出小计: Cash_outflow_for_investment_activities
投资活动产生的现金流量净额: Net_investment_activities_generated_cash_flow
吸收投资收到的现金: Receipts_from_equity_securities
子公司吸收少数股东投资收到的现金: subsidiary_minority_shareholders_investment_cash_received
取得借款收到的现金: Receipts_from_loan
发行债券收到的现金: The_cash_that_received_to_issue_bonds
收到其他与筹资活动有关的现金: Cash_received_relating_to_other_financing_activities
筹资活动现金流入小计: Cash_inflow_from_financing_activities
偿还债务支付的现金: Payment_for_debt
分配股利、利润或偿付利息所支付的现金: Payment_for_dividend_and_interest
支付其他与筹资活动有关的现金: Payment_for_other_finance_activites
筹资活动现金流出小计: Cash_outflow_for_financing_activities
筹资活动产生的现金流量净额: The_net_cash_flow_generated_by_financing_activities
汇率变动对现金及现金等价物的影响: impact_of_exchange_rate_movements_of_cash_cash_equivalents
现金及现金等价物净增加额: Net_increase_in_cash_and_cash_equivalents
期初现金及现金等价物余额: The_beginning_balance_of_cash_and_cash_equivalents
期末现金及现金等价物余额: The_final_balance_of_cash_and_cash_equivalents
净利润: Net_profit
少数股东权益: minority_interest
未确认的投资损失: Unrecognized_investment_losses
资产减值准备: Property_depreciation_preparation
固定资产折旧、油气资产折耗、生产性物资折旧: fixed_assets_oil_gas_produmaterial_depreciation
无形资产摊销: Amortisation_of_intangible_assets
长期待摊费用摊销: Amortisation_of_long_term_deferred_expenses
待摊费用的减少: Deferred_and_prepaid_expenses_decrease
预提费用的增加: Accrued_expense_increase
处置固定资产、无形资产和其他长期资产的损失: disposal_of_fixed_intangible_other_long_term_assets_loss
固定资产报废损失: Losses_on_write_off_of_fixed_assets
公允价值变动损失: Loss_from_Fair_Value_Change
递延收益增加（减：减少）: Deferred_revenue_increase
预计负债: Anticipation_liabilities
财务费用: financial_expenses
投资损失: investment_loss
递延所得税资产减少: Deferred_tax_assets
递延所得税负债增加: Deferred_income_tax_liabilities
存货的减少: The_decrease_of_inventory
经营性应收项目的减少: A_drop_in_business_receivables
经营性应付项目的增加: Business_to_cope_with_the_increase_of_the_project
已完工尚未结算款的减少(减:增加): Completed_yet_settlement_of_decrease
已结算尚未完工款的增加(减:减少): Already_settlement_unfinished_increase
其他: other
经营活动产生现金流量净额: cash_flows_generated_from_operating_activities
债务转为资本: Conversion_of_debt_into_capital
一年内到期的可转换公司债券: Convertible_bonds_matured_within_a_year
融资租入固定资产: fixed_assets_financed_by_leasing
现金的期末余额: The_ending_balance_of_cash
现金的期初余额: The_beginning_balance_of_cash
现金等价物的期末余额: The_ending_balance_of_cash_equivalents
现金等价物的期初余额: The_beginning_balance_of_cash
现金等价物的期初余额: The_beginning_balance_of_cash_equivalents
现金及现金等价物的净增加额: Net_increase_in_cash_and_cash_equivalents





