报表日期: report_date
一、营业总收入: gross_revenue
营业收入: operating_income
利息收入: interest_income
已赚保费: earned_premium
手续费及佣金收入: fee_and_commission_income
房地产销售收入: real_estate_sales
其他业务收入: other_operating_revenue
二、营业总成本: total_operating_cost
营业成本: operating_cost
利息支出: interest_expense
手续费及佣金支出: fee_and_commission_expenses
房地产销售成本: real_estate_sales_cost
研发费用: research_development_expense
退保金: surrender_value
赔付支出净额: net_payments_for_insurance_claims
提取保险合同准备金净额: net_provision_for_insurance_contracts
保单红利支出: bond_insurance_expense
分保费用: amortized_reinsurance_expenditures
其他业务成本: other_operational_costs
营业税金及附加: business_tariff_and_annex
销售费用: sales_costs
管理费用: management_cost
财务费用: finance_charges
资产减值损失: asset_impairment_loss
公允价值变动收益: changes_in_the_fair_value_earnings
投资收益: investment_income
对联营企业和合营企业的投资收益: associated_enterprises_and_joint_venture_investment_income
汇兑收益: foreign_exchange_earnings
期货损益: profit_and_loss_of_futures
托管收益: managed_earnings
补贴收入: subsidize_revenue
其他业务利润: income_from_other_operation
三、营业利润: operating_profit
营业外收入: non_operating_income
营业外支出: nonbusiness_expenditure
非流动资产处置损失: disposal_loss_on_noncurrent_liability
利润总额: total_Profits
所得税费用: income_tax_expenses
未确认投资损失: unrealised_investment_losses
四、净利润: net_profit
归属于母公司所有者的净利润: net_profit_attributable_to_parent_company_owners
少数股东损益: minority_interests
五、每股收益: earnings_per_share
基本每股收益: basic_earnings_per_share_yuan
稀释每股收益: diluted_earnings_per_share_yuan
六、其他综合收益: oci
七、综合收益总额: aggregate_comprehensive_income
归属于母公司所有者的综合收益总额: total_comprehensive_income_attributable_to_parent_company_owners
归属于少数股东的综合收益总额: total_comprehensive_income_attributable_to_minority_shareholders