class CreateBalanceSheetReport < ActiveRecord::Migration
  def change
    create_table :balance_sheet_reports do |t|
      t.string :code
      t.string :name
      t.string :industry
      t.time :report_date #报表日期
      t.float :cash_and_cash_equivalents
      t.float :deposit_reservation_for_balance
      t.float :loans_to_others_banks
      t.float :transaction_monetary_assets
      t.float :derivative_financial_assets
      t.float :notes_receivable
      t.float :account_receivable
      t.float :prepayments
      t.float :premiums_receivable
      t.float :reinsurance_accounts_receivable
      t.float :receivable_from_subcontracting_reserves
      t.float :interest_receivable
      t.float :dividend_receivable
      t.float :other_receivables
      t.float :export_drawback_receivable
      t.float :allowance_receivable
      t.float :margin_receivable
      t.float :internal_receivables
      t.float :redemptory_monetary_capital_for_sale
      t.float :inventory
      t.float :deferred_and_prepaid_expenses
      t.float :current_asset_losses_in_suspense
      t.float :noncurrent_assets_matured_within_a_year
      t.float :other_current_assets
      t.float :total_current_assets
      t.float :loans_and__advance
      t.float :financial_assets_available_for_sale
      t.float :held_to_maturity_investments
      t.float :long_term_account_receivable
      t.float :long_term_equity_investments
      t.float :other_long_term_investment
      t.float :investment_real_estate
      t.float :original_value_of_fixed_assets
      t.float :accumulated_depreciation
      t.float :fixed_assets_net_value
      t.float :fixed_assets_depreciation_reserves
      t.float :net_value_of_fixed_assets
      t.float :construction_in_progress
      t.float :project_goods_and_material
      t.float :disposal_of_fixed_assets
      t.float :capitalized_biological_assets
      t.float :non_profit_living_assets
      t.float :oil_gas_assets
      t.float :intangible_asset
      t.float :development_disbursement
      t.float :goodwill
      t.float :long_term_deferred_and_prepaid_expenses
      t.float :circulation_right_for_equity_separatio
      t.float :deferred_income_tax_assets
      t.float :other_non_current_assets
      t.float :total_non_current_assets
      t.float :total_assets
      t.float :short_term_borrowings
      t.float :borrowings_from_central_bank
      t.float :deposits_from_customers_and_interbank
      t.float :loans_from_other_banks
      t.float :transaction_financial_liabilities
      t.float :derivative_financial_liability
      t.float :notes_payable
      t.float :accounts_payable
      t.float :account_collected_in_advance
      t.float :financial_assets_sold_for_repurchase
      t.float :handling_charges_and_commissions_payable
      t.float :employee_pay_payable
      t.float :tax_payable
      t.float :accrued_interest_payable
      t.float :dividends_payable
      t.float :other_payable_to_government
      t.float :margin_requirement
      t.float :internal_accouts_receivable
      t.float :other_payables
      t.float :accrued_expenses
      t.float :expected_to_current_liabilities
      t.float :dividend_payable_for_reinsurance
      t.float :provision_for_insurance_contracts
      t.float :receivings_from_vicariously_traded_securities
      t.float :acting_underwriting_securities
      t.float :international_ticket_settlement
      t.float :domestic_ticket_settlement
      t.float :deferred_income
      t.float :short_term_debentures_payable
      t.float :non_current_liabilities_due_within_one_year
      t.float :other_current_liabilities
      t.float :total_current_liabilities
      t.float :long_term_loans
      t.float :bonds_payable
      t.float :long_term_account_payable
      t.float :special_payables
      t.float :expect_non_current_liabilities
      t.float :deferred_income_tax_liabilities
      t.float :other_non_current_liabilities
      t.float :total_non_current_liabilities
      t.float :total_liabilities
      t.float :paid_up_capital
      t.float :capital_reserves
      t.float :treasury_stock
      t.float :special_reserves
      t.float :surplus_reserves
      t.float :generic_risk_reserve
      t.float :uncertain_investment_losses
      t.float :undistributed_profit
      t.float :distribution_of_cash_dividend
      t.float :translation_reserve
      t.float :attributable_to_the_parent_company_shareholders_equity_in_total
      t.float :minority_interest
      t.float :shareholders_equity_combined
      t.float :liabilities_and_shareholders_equity_in_total
      t.timestamps
    end
    add_index :balance_sheet_reports, [:code, :report_date], :unique => true

  end
end